import{
    GET_PROPERTIES,
    ADD_PROPERTY,
    DELETE_PROPERTY,
    SET_CURRENT,
    CLEAR_CURRENT,
    UPDATE_PROPERTY,
    FILTER_PROPERTIES,
    CLEAR_PROPERTIES,
    CLEAR_FILTER,
    PROPERTY_ERROR,

} from "../types";